/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/exams/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of all created exams */
        get: operations["get_exams"];
        put?: never;
        /** Create a new exam (Admin Only) */
        post: operations["post_exams"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exams/{exam_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: number;
            };
            cookie?: never;
        };
        /** Get details of a specific exam */
        get: operations["get_exam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hello/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_hello_world"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Exam: {
            /**
             * @description Exam ID
             * @example 1
             */
            id: number;
            /**
             * @description Exam name
             * @example Math Exam
             */
            title: string;
            /**
             * @description Subject name
             * @example Math
             */
            subject: string;
            /**
             * @description Grade for the exam
             * @example pre-IB or 11
             */
            grade: string;
        };
    };
    responses: {
        /** @description When a mask can't be parsed */
        ParseError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description When any error occurs on mask */
        MaskError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_exams: {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional fields mask */
                "X-Fields"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"][];
                };
            };
        };
    };
    post_exams: {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional fields mask */
                "X-Fields"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exam"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
        };
    };
    get_exam: {
        parameters: {
            query?: never;
            header?: {
                /** @description An optional fields mask */
                "X-Fields"?: string;
            };
            path: {
                exam_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exam"];
                };
            };
            /** @description Exam not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_hello_world: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
